apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-metrics-servicemonitor
  # Change this to the namespace the Prometheus instance is running in
  namespace: monitoring
  labels:
    app: wordpress
    release: prometheus
spec:
  selector:
    matchLabels:
      role: db # target db service
  endpoints:
  - port: metrics
    interval: 15s
