apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
  - name: jenkins-port
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: slave
    port: 5000
    targetPort: 5000
    protocol: TCP