kind: PersistentVolume
apiVersion: v1
metadata:  
  name: persistent-storage  
  labels:    
    type: local
    volume: mysql-vol
spec:  
  storageClassName: manual  
  capacity:    
    storage: 4Gi  
  persistentVolumeReclaimPolicy: Recycle  
  accessModes:
    - ReadWriteOnce  
  hostPath:    
    path: "/var/lib/pv1"
---
kind: PersistentVolume
apiVersion: v1
metadata:  
  name: persistent-storage-wp
  labels:    
    type: local
    volume: wp-vol
spec:  
  storageClassName: manual  
  capacity:    
    storage: 2Gi  
  persistentVolumeReclaimPolicy: Recycle  
  accessModes:
    - ReadWriteOnce  
  hostPath:    
    path: "/var/lib/pv2"
